import {Message} from "roslib";
import * as actionlib_msgs from "./actionlib_msgs";
import * as geometry_msgs from "./geometry_msgs";
import * as std_msgs from "./std_msgs";

export class MoveBaseAction extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */

    action_goal: MoveBaseActionGoal;
    action_result: MoveBaseActionResult;
    action_feedback: MoveBaseActionFeedback;

    constructor(values: {
        action_goal?: MoveBaseActionGoal;
        action_result?: MoveBaseActionResult;
        action_feedback?: MoveBaseActionFeedback;
    }) {
        super(values);
    }
}

export class MoveBaseActionGoal extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */

    header: std_msgs.Header;
    goal_id: actionlib_msgs.GoalID;
    goal: MoveBaseGoal;

    constructor(values: {
        header?: std_msgs.Header;
        goal_id?: actionlib_msgs.GoalID;
        goal?: MoveBaseGoal;
    }) {
        super(values);
    }
}

export class MoveBaseFeedback extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */
    base_position: geometry_msgs.PoseStamped;

    constructor(values: {
        base_position?: geometry_msgs.PoseStamped;
    }) {
        super(values);
    }
}

export class MoveBaseResult extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */
    constructor(values: {}) {
        super(values);
    }
}

export class MoveBaseActionFeedback extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */

    header: std_msgs.Header;
    status: actionlib_msgs.GoalStatus;
    feedback: MoveBaseFeedback;

    constructor(values: {
        header?: std_msgs.Header;
        status?: actionlib_msgs.GoalStatus;
        feedback?: MoveBaseFeedback;
    }) {
        super(values);
    }
}

export class MoveBaseActionResult extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */

    header: std_msgs.Header;
    status: actionlib_msgs.GoalStatus;
    result: MoveBaseResult;

    constructor(values: {
        header?: std_msgs.Header;
        status?: actionlib_msgs.GoalStatus;
        result?: MoveBaseResult;
    }) {
        super(values);
    }
}

export class MoveBaseGoal extends Message {
    /** ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ====== */
    target_pose: geometry_msgs.PoseStamped;

    constructor(values: {
        target_pose?: geometry_msgs.PoseStamped;
    }) {
        super(values);
    }
}
